import { UserProvider } from './store/user'

import Layout from './components/Layout'

import './styles/globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <UserProvider>
        <Layout>
          { children }
        </Layout>
      </UserProvider>
    </html>
  )
}
